### PR TITLE
force pulling tags in actions to overwrite github local copy

### PR DESCRIPTION
**Pull request by jmtcsngr**

### CODE REVIEW

**Comment by jmtcsngr** [comment]
See error reported in

https://github.com/wtsi-npg/npg_ml_warehouse/runs/7505658019?check_suite_focus=true

**Comment by mksanger** [comment]
This looks fine to me, it matches how we pull tags for partisan and ml-warehouse python.  If you rebase it, I'll merge.

**Comment by mksanger** [comment]
I see no reason not to keep fetching the tags with --force.  Equally, I don't think it would be a great loss to remove that action from the file, its up to you @jmtcsngr.

**Comment by jmtcsngr** [comment]
@mksanger rebased :)

**Pull request merged**
